version: '3.1'
services:
  stats-server:
    build: explore-stats/stat-server/
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statServiceDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
    depends_on:
      - stats-db

  stats-db:
    image: postgres:14-alpine
    ports:
      - "5437:5432"
    container_name: stats-db-container
    environment:
      - POSTGRES_DB=statServiceDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  explore-main-db:
    image: postgres:14-alpine
    ports:
      - "5438:5432"
    container_name: explore-main-db-container
    environment:
      - POSTGRES_DB=exploreMainServiceDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  explore-main-server:
    build: explore-main/
    ports:
      - "8080:8080"
    depends_on:
      - explore-main-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://explore-main-db:5432/exploreMainServiceDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
      - STAT_SERVER_URL=http://stats-server:9090
