DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS CATEGORIES CASCADE;
DROP TABLE IF EXISTS EVENTS CASCADE;
DROP TABLE IF EXISTS REQUESTS CASCADE;
DROP TABLE IF EXISTS COMPILATIONS CASCADE;
DROP TABLE IF EXISTS COMPILATION_EVENT CASCADE;

CREATE TABLE IF NOT EXISTS USERS
(
    USER_ID BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL
        primary key
        unique,
    NAME    CHARACTER VARYING,
    EMAIL   CHARACTER VARYING                       not null
        unique
);

CREATE TABLE IF NOT EXISTS CATEGORIES
(
    CATEGORY_ID BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL
        primary key
        unique,
    NAME        CHARACTER VARYING                       not null
        unique
);

CREATE TABLE IF NOT EXISTS EVENTS
(
    event_id           BIGINT        NOT NULL GENERATED BY DEFAULT AS IDENTITY primary key,
    annotation         VARCHAR(2000) NOT NULL,
    category_id        BIGINT        NOT NULL REFERENCES CATEGORIES (CATEGORY_ID),
    create_date        TIMESTAMP,
    description        VARCHAR(7000) NOT NULL,
    event_date         TIMESTAMP,
    initiator_id       BIGINT        NOT NULL REFERENCES USERS (USER_ID),
    lat                FLOAT         NOT NULL,
    lon                FLOAT         NOT NULL,
    paid               BOOLEAN       NOT NULL,
    participant_limit  BIGINT        NOT NULL,
    available          BOOLEAN,
    published_on       TIMESTAMP,
    request_moderation BOOLEAN       NOT NULL,
    state              VARCHAR       NOT NULL,
    title              VARCHAR(120)  NOT NULL,
    event_views        BIGINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS REQUESTS
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL
        primary key,
    created      TIMESTAMP                               NOT NULL,
    event_id     BIGINT                                  NOT NULL REFERENCES EVENTS (EVENT_ID),
    requester_id BIGINT                                  NOT NULL REFERENCES USERS (USER_ID),
    status       VARCHAR(32)                             NOT NULL
);

CREATE TABLE IF NOT EXISTS COMPILATIONS
(
    compilation_id    BIGINT  NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned            BOOLEAN NOT NULL,
    compilation_title VARCHAR NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS COMPILATION_EVENT
(
    event_id       BIGINT NOT NULL REFERENCES events (EVENT_ID) ON DELETE CASCADE,
    compilation_id BIGINT NOT NULL REFERENCES compilations (compilation_id) ON DELETE CASCADE
);

